"""create face_embedding table

Revision ID: 032ceaac0575
Revises: 434b6acc2c5f
Create Date: 2026-07-06 16:05:25.012728+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032ceaac0575'
down_revision: Union[str, None] = '434b6acc2c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embedding',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_uuid', sa.String(length=36), nullable=False),
    sa.Column('embedding', sa.LargeBinary(length=2048), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_uuid'], ['utilisateur.uuid'], name=op.f('fk_face_embedding_utilisateur_uuid_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embedding'))
    )
    op.create_index(op.f('ix_face_embedding_active'), 'face_embedding', ['active'], unique=False)
    op.create_index(op.f('ix_face_embedding_utilisateur_uuid'), 'face_embedding', ['utilisateur_uuid'], unique=False)
    op.create_index(op.f('ix_face_embedding_uuid'), 'face_embedding', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embedding_uuid'), table_name='face_embedding')
    op.drop_index(op.f('ix_face_embedding_utilisateur_uuid'), table_name='face_embedding')
    op.drop_index(op.f('ix_face_embedding_active'), table_name='face_embedding')
    op.drop_table('face_embedding')
    # ### end Alembic commands ###
