"""initial_schema

Revision ID: 434b6acc2c5f
Revises: 
Create Date: 2026-07-05 10:42:30.543204+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434b6acc2c5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie_repas',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorie_repas'))
    )
    op.create_index(op.f('ix_categorie_repas_nom'), 'categorie_repas', ['nom'], unique=True)
    op.create_index(op.f('ix_categorie_repas_uuid'), 'categorie_repas', ['uuid'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_index(op.f('ix_role_nom'), 'role', ['nom'], unique=True)
    op.create_index(op.f('ix_role_uuid'), 'role', ['uuid'], unique=True)
    op.create_table('utilisateur',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('EMPLOYE', 'STAGIAIRE', 'VISITEUR', 'ADMINISTRATEUR', 'RECEPTION', name='typeutilisateur'), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', 'SUPPRIME', name='statututilisateur'), nullable=False),
    sa.Column('langue', sa.Enum('FR', 'AR', 'EN', name='langue'), nullable=True),
    sa.Column('date_suppression', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateur'))
    )
    op.create_index(op.f('ix_utilisateur_created_by_id'), 'utilisateur', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_nom'), 'utilisateur', ['nom'], unique=False)
    op.create_index(op.f('ix_utilisateur_prenom'), 'utilisateur', ['prenom'], unique=False)
    op.create_index(op.f('ix_utilisateur_statut'), 'utilisateur', ['statut'], unique=False)
    op.create_index(op.f('ix_utilisateur_updated_by_id'), 'utilisateur', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_utilisateur_uuid'), 'utilisateur', ['uuid'], unique=True)
    op.create_foreign_key(op.f('fk_utilisateur_created_by_id_utilisateur'), 'utilisateur', 'utilisateur', ['created_by_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_utilisateur_updated_by_id_utilisateur'), 'utilisateur', 'utilisateur', ['updated_by_id'], ['uuid'], ondelete='SET NULL')
    op.create_table('administrateur',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentatives_echouees', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], name=op.f('fk_administrateur_id_utilisateur'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_administrateur_role_id_role'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrateur'))
    )
    op.create_index(op.f('ix_administrateur_role_id'), 'administrateur', ['role_id'], unique=False)
    op.create_table('employe',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('date_enrolement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut_enrolement', sa.Enum('NON_ENROLE', 'ENROLE', 'ENROLEMENT_ECHOUE', name='statutenrolement'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], name=op.f('fk_employe_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employe'))
    )
    op.create_index(op.f('ix_employe_matricule'), 'employe', ['matricule'], unique=True)
    op.create_index(op.f('ix_employe_statut_enrolement'), 'employe', ['statut_enrolement'], unique=False)
    op.create_table('qr_code',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('qr_hash', sa.String(length=255), nullable=False),
    sa.Column('proprietaire_uuid', sa.String(length=36), nullable=False),
    sa.Column('type_proprietaire', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_uuid', sa.String(length=36), nullable=True),
    sa.Column('date_revocation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoque_par_uuid', sa.String(length=36), nullable=True),
    sa.Column('motif_revocation', sa.String(length=100), nullable=True),
    sa.Column('derniere_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_validations', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_uuid'], ['utilisateur.uuid'], name=op.f('fk_qr_code_cree_par_uuid_utilisateur')),
    sa.ForeignKeyConstraint(['proprietaire_uuid'], ['utilisateur.uuid'], name=op.f('fk_qr_code_proprietaire_uuid_utilisateur')),
    sa.ForeignKeyConstraint(['revoque_par_uuid'], ['utilisateur.uuid'], name=op.f('fk_qr_code_revoque_par_uuid_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_code'))
    )
    op.create_index(op.f('ix_qr_code_proprietaire_uuid'), 'qr_code', ['proprietaire_uuid'], unique=False)
    op.create_index(op.f('ix_qr_code_qr_hash'), 'qr_code', ['qr_hash'], unique=True)
    op.create_index(op.f('ix_qr_code_statut'), 'qr_code', ['statut'], unique=False)
    op.create_index(op.f('ix_qr_code_uuid'), 'qr_code', ['uuid'], unique=True)
    op.create_table('reception',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], name=op.f('fk_reception_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reception'))
    )
    op.create_table('stagiaire',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('date_debut_stage', sa.Date(), nullable=False),
    sa.Column('date_fin_stage', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], name=op.f('fk_stagiaire_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stagiaire'))
    )
    op.create_index(op.f('ix_stagiaire_date_fin_stage'), 'stagiaire', ['date_fin_stage'], unique=False)
    op.create_index(op.f('ix_stagiaire_matricule'), 'stagiaire', ['matricule'], unique=True)
    op.create_table('visiteur',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('societe', sa.String(length=255), nullable=True),
    sa.Column('date_visite', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], name=op.f('fk_visiteur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visiteur'))
    )
    op.create_index(op.f('ix_visiteur_date_visite'), 'visiteur', ['date_visite'], unique=False)
    op.create_table('repas',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_uuid', sa.String(length=36), nullable=False),
    sa.Column('qr_uuid', sa.String(length=36), nullable=True),
    sa.Column('categorie_uuid', sa.String(length=36), nullable=False),
    sa.Column('type_identification', sa.String(length=20), nullable=False),
    sa.Column('date_repas', sa.Date(), nullable=False),
    sa.Column('heure_repas', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enregistre_par_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categorie_uuid'], ['categorie_repas.uuid'], name=op.f('fk_repas_categorie_uuid_categorie_repas')),
    sa.ForeignKeyConstraint(['enregistre_par_uuid'], ['utilisateur.uuid'], name=op.f('fk_repas_enregistre_par_uuid_utilisateur')),
    sa.ForeignKeyConstraint(['qr_uuid'], ['qr_code.uuid'], name=op.f('fk_repas_qr_uuid_qr_code')),
    sa.ForeignKeyConstraint(['utilisateur_uuid'], ['utilisateur.uuid'], name=op.f('fk_repas_utilisateur_uuid_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repas')),
    sa.UniqueConstraint('utilisateur_uuid', 'date_repas', name='uq_repas_utilisateur_date')
    )
    op.create_index(op.f('ix_repas_categorie_uuid'), 'repas', ['categorie_uuid'], unique=False)
    op.create_index(op.f('ix_repas_date_repas'), 'repas', ['date_repas'], unique=False)
    op.create_index(op.f('ix_repas_qr_uuid'), 'repas', ['qr_uuid'], unique=False)
    op.create_index(op.f('ix_repas_utilisateur_uuid'), 'repas', ['utilisateur_uuid'], unique=False)
    op.create_index(op.f('ix_repas_uuid'), 'repas', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repas_uuid'), table_name='repas')
    op.drop_index(op.f('ix_repas_utilisateur_uuid'), table_name='repas')
    op.drop_index(op.f('ix_repas_qr_uuid'), table_name='repas')
    op.drop_index(op.f('ix_repas_date_repas'), table_name='repas')
    op.drop_index(op.f('ix_repas_categorie_uuid'), table_name='repas')
    op.drop_table('repas')
    op.drop_index(op.f('ix_visiteur_date_visite'), table_name='visiteur')
    op.drop_table('visiteur')
    op.drop_index(op.f('ix_stagiaire_matricule'), table_name='stagiaire')
    op.drop_index(op.f('ix_stagiaire_date_fin_stage'), table_name='stagiaire')
    op.drop_table('stagiaire')
    op.drop_table('reception')
    op.drop_index(op.f('ix_qr_code_uuid'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_statut'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_qr_hash'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_proprietaire_uuid'), table_name='qr_code')
    op.drop_table('qr_code')
    op.drop_index(op.f('ix_employe_statut_enrolement'), table_name='employe')
    op.drop_index(op.f('ix_employe_matricule'), table_name='employe')
    op.drop_table('employe')
    op.drop_index(op.f('ix_administrateur_role_id'), table_name='administrateur')
    op.drop_table('administrateur')
    op.drop_constraint(op.f('fk_utilisateur_updated_by_id_utilisateur'), 'utilisateur', type_='foreignkey')
    op.drop_constraint(op.f('fk_utilisateur_created_by_id_utilisateur'), 'utilisateur', type_='foreignkey')
    op.drop_index(op.f('ix_utilisateur_uuid'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_updated_by_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_statut'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_prenom'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_nom'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_created_by_id'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_role_uuid'), table_name='role')
    op.drop_index(op.f('ix_role_nom'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_categorie_repas_uuid'), table_name='categorie_repas')
    op.drop_index(op.f('ix_categorie_repas_nom'), table_name='categorie_repas')
    op.drop_table('categorie_repas')
    # ### end Alembic commands ###
